export default {
  BASE_URL: process.env.REACT_APP_BASE_URL,
  UPLOAD_BASE_URL: process.env.REACT_APP_UPLOAD_BASE_URL,
  CLOUD_NAME: process.env.REACT_APP_CLOUD_NAME,
  UPLOAD_PRESET: process.env.REACT_APP_UPLOAD_PRESET,
  PAGE_SIZE: process.env.REACT_APP_ARTICLES_PAGE_SIZE || 10,
  PLACEHOLDER_IMAGE: process.env.REACT_APP_PLACEHOLDER_IMAGE,
  SHARE_URL: process.env.REACT_APP_SHARE_URL,
  DEFAULT_AVATAR: process.env.REACT_APP_DEFAULT_AVATAR,
  MAX_DESCRIPTION_SIZE: 200,
  SEARCH_MIN_CHARS: 1,
  SEARCH_DELAY: 200,
};
